title: Archetype
baseurl: /
permalink: '/:title/'
landing_template: home
palette: blue
palettes:
  blue:
    sass:
      gradient1: '#27a1e3'
      gradient2: '#e7232a'
      accent1: '#5f9dd2'
      accent2: '#758ce1'
      accent3: '#e286a9'
  green:
    sass:
      gradient1: '#16f4cf'
      gradient2: '#6532e5'
      accent1: '#54d3cf'
      accent2: '#4f92d1'
      accent3: '#8075e5'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
